version = 0.1

[default.deploy.parameters]
stack_name = "tl-lambda-ping-sam"
resolve_s3 = true
s3_prefix = "tl-lambda-ping-sam"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = false

[default.global.parameters]
region = "eu-central-1"
